"""agregar imagen_encabezado e imagen_pie a empresa

Revision ID: 56d82524755d
Revises: df08dc1086a7
Create Date: 2026-08-11 13:16:39.843731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56d82524755d'
down_revision: Union[str, Sequence[str], None] = 'df08dc1086a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresa', sa.Column('imagen_encabezado', sa.String(length=255), nullable=True))
    op.add_column('empresa', sa.Column('imagen_pie', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresa', 'imagen_pie')
    op.drop_column('empresa', 'imagen_encabezado')
    # ### end Alembic commands ###
