"""cotizaciones: agregar forma_pago y descuento

Revision ID: 5b5d7b979768
Revises: 975c725d69a1
Create Date: 2026-08-12 14:33:23.589007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b5d7b979768'
down_revision: Union[str, Sequence[str], None] = '975c725d69a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cotizaciones', sa.Column('forma_pago', sa.String(length=50), nullable=False, server_default=''))
    op.add_column('cotizaciones', sa.Column('descuento', sa.DECIMAL(precision=10, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cotizaciones', 'descuento')
    op.drop_column('cotizaciones', 'forma_pago')
    # ### end Alembic commands ###
