"""cotizaciones: tablas de cotizacion y detalles_cotizacion

Revision ID: 975c725d69a1
Revises: 56d82524755d
Create Date: 2026-08-11 22:24:33.817011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '975c725d69a1'
down_revision: Union[str, Sequence[str], None] = '56d82524755d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cotizaciones',
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('con_factura', sa.Boolean(), nullable=True),
    sa.Column('incluir_imagenes', sa.Boolean(), nullable=True),
    sa.Column('modalidad_pago', sa.String(length=100), nullable=False),
    sa.Column('validez_dias', sa.Integer(), nullable=False),
    sa.Column('terminos_condiciones', sa.Text(), nullable=False),
    sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('iva', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('venta_id', sa.Integer(), nullable=True),
    sa.Column('cliente_razon_social', sa.String(length=100), nullable=False),
    sa.Column('cliente_nit', sa.String(length=20), nullable=False),
    sa.Column('cliente_celular', sa.String(length=20), nullable=False),
    sa.Column('cliente_direccion', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('detalles_cotizacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cotizacion_id', sa.Integer(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('costo', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('utilidad_pct', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('precio_venta', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizaciones.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalles_cotizacion')
    op.drop_table('cotizaciones')
    # ### end Alembic commands ###
