"""producto: procedencia, stock_maximo, imagen; quitar peso

Revision ID: df08dc1086a7
Revises: 6ccf96e83613
Create Date: 2026-08-10 10:30:27.666645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'df08dc1086a7'
down_revision: Union[str, Sequence[str], None] = '6ccf96e83613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('procedencia', sa.String(length=100), nullable=False, server_default=''))
    op.add_column('productos', sa.Column('stock_maximo', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('productos', sa.Column('imagen', sa.String(length=255), nullable=True))
    op.drop_column('productos', 'peso')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('peso', mysql.DECIMAL(precision=10, scale=2), nullable=False))
    op.drop_column('productos', 'imagen')
    op.drop_column('productos', 'stock_maximo')
    op.drop_column('productos', 'procedencia')
    # ### end Alembic commands ###
