
CREATE TABLE roles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE modulos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL UNIQUE,
  activo TINYINT(1) DEFAULT 1
);

CREATE TABLE rol_modulo (
  id INT AUTO_INCREMENT PRIMARY KEY,
  rol_id INT,
  modulo_id INT,
  FOREIGN KEY (rol_id) REFERENCES roles(id),
  FOREIGN KEY (modulo_id) REFERENCES modulos(id)
);

CREATE TABLE usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  nombres VARCHAR(100) NOT NULL,
  apellidos VARCHAR(100) NOT NULL,
  cargo VARCHAR(100) NOT NULL,
  rol_id INT NOT NULL,
  fecha_registro DATETIME DEFAULT NOW(),
  fecha_actualizado DATETIME DEFAULT NOW() ON UPDATE NOW(),
  activo TINYINT(1) DEFAULT 1,
  FOREIGN KEY (rol_id) REFERENCES roles(id)
);

CREATE TABLE categorias (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL
);

CREATE TABLE comprobantes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL,
  numero INT DEFAULT 1 NOT NULL
);

CREATE TABLE estados (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL
);

CREATE TABLE transacciones (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL
);
